version: '3.5'

services:
  app:
    image: jaderh/docker-nginx-php-supervisor:mt
    ports:
      - 80:80
      - 443:443
    environment:
      TZ: Asia/Shanghai
    volumes:
      - /Users/jade/MingYuanYun/code:/webser/www
      - ./config/mt.conf:/etc/nginx/conf.d/mt.conf