version: '3.5'

services:
  app:
    build: .
    ports:
      - 80:80
      - 443:443
    environment:
      TZ: Asia/Shanghai
    volumes:
      - /Users/jade/MingYuanYun/code:/webser/www
      - ./config/cl-mall.conf:/etc/nginx/conf.d/cl-mall.conf